# Generated by Django 5.2.1 on 2025-05-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], max_length=20)),
                ('data_entrega', models.DateField()),
            ],
        ),
    ]
